services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp" # Initial setup
      - "853:853/tcp"  # DNS-over-TLS
      - "784:784/udp"  # DNS-over-QUIC
    volumes:
      - ./data:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
      - aether-net
    labels:
      - "com.docker.compose.project=${STACK_NAME}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adguard.rule=Host(`${ADGUARD_SUBDOMAIN}.${DOMAIN_NAME}`)"
        - "traefik.http.routers.adguard.entrypoints=websecure"
        - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
        - "traefik.http.services.adguard.loadbalancer.server.port=3000"
        - "traefik.http.routers.adguard.middlewares=authelia"
      restart_policy:
        condition: on-failure

networks:
  aether-net:
    external: true
